version: '3'

services:
  elaastic-questions-db-8:
    image: mysql:8.3
    container_name: elaastic-questions-db-8
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6683:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - db_data:/var/lib/mysql
  elaastic-questions-server:
    image: elaastic/elaastic-questions-server:latest
    container_name: elaastic-questions-server
    volumes:
      - ./docker-resources/elaastic-questions-server/configuration/:/configuration/
      - ./docker-resources/elaastic-questions-server/certificates/:/certificates/
      - datastore:/datastore/
      - tmp:/tmp/
    depends_on:
      - elaastic-questions-db-8
    ports:
      - "8081:8080"
    environment:
      - USE_SYSTEM_CA_CERTS=1
      - DATABASE_HOST=elaastic-questions-db-8
      - DATABASE_USER=elaastic
      - DATABASE_NAME=elaastic-questions
      - DATABASE_PASSWORD=elaastic
      - DATABASE_PORT=3306
volumes:
  datastore: # For storing attachments
  db_data: # For storing data from DB
  tmp: # for temporary files
